# Generated by Django 3.2.25 on 2024-06-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobbavoca', '0003_auto_20240622_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='created_date',
            new_name='timestamp',
        ),
    ]
